### ISSUE TITLE
打錯

### ISSUE THREAD

**Issue by tary159951123** [roberthsu2003/__2024_04_17_mon_wed__#2]
#計算圓面積

**Comment by tary159951123** [comment]
> #計算圓面積 import math print("計算圓面積") radius:float = float(input("請輸入半徑:")) area:float = math.pi * radius ** 2 print(f"圓半徑:{radius},圓面積:{math.pi * radius ** 2:.5f}") print(f"圓半徑:{radius},圓面積:{area}") print(f"圓半徑:{radius:.5f},圓面積:{area:.2f}") d = 2 * radius print(圆直径: {d:.2f})

**Comment by tary159951123** [comment]
`> #計算圓面積 import math print("計算圓面積") radius:float = float(input("請輸入半徑:")) area:float = math.pi * radius ** 2 print(f"圓半徑:{radius},圓面積:{math.pi * radius ** 2:.5f}") print(f"圓半徑:{radius},圓面積:{area}") print(f"圓半徑:{radius:.5f},圓面積:{area:.2f}") d = 2 * radius print(圆直径: {d:.2f}
`

**Comment by drama554** [comment]
老師這是什麼意思？

徐國堂 ***@***.***>於 2024年4月26日 週五，12:02寫道：

**Comment by roberthsu2003** [comment]
請將練習答案寫在issue1。
